### ISSUE TITLE
requiring 'emoji/railtie' is deprecated. Please manually add Emoji.images_path to your config.assets.paths.

### ISSUE THREAD

**Issue by pavankat** [rubysherpas/forem#605]
I'm getting this with a Rails 4.1.4 app using forem rails 4 gem:

requiring 'emoji/railtie' is deprecated. Please manually add Emoji.images_path to your config.assets.paths.

`Rails.application.config.assets.precompile += %w( forem.css forem.js emoji/smile.png)`

**Comment by radar** [comment]
I think this was fixed by #602. Can you please try upgrading and see if that fixes your issue?

**Comment by pavankat** [comment]
@radar I have the latest version I think. And it's still not working.

  remote: git://github.com/radar/forem.git
  revision: 1a776b8d847701eceb88ddaa27a176ba238fbae9
  branch: rails4
  specs:
    forem (1.0.0.beta1)
      cancancan (~> 1.7)
      decorators (~> 1.0.2)
      friendly_id (~> 5.0.0)
      gemoji (= 2.1.0)
      rails (>= 4.0.3, <= 4.1.6)
      sanitize (= 2.0.6)
      select2-rails (~> 3.5.4)
      simple_form (~> 3.0.1)
      workflow (= 1.0.0)

**Comment by radar** [comment]
@pavankat you are currently 3 commits behind `rails4` HEAD.

```
38ff418 Bump devise dependency to 3.3.0
69b6b7a Merge pull request #602 from pierallard/rails4
4c7c407 Remove deprecation warning for emoji
```

The first two (the bottom two) commits in that range are the two commits that will fix the issue that you're seeing. Please run `bundle update forem`.

**Comment by pavankat** [comment]
thank you @radar!
