### ISSUE TITLE
undefined local variable or method `forem_user'

### ISSUE THREAD

**Issue by mickfeech** [rubysherpas/forem#90]
After running rails g forem:install and starting my app, I goto /forums and I'm getting the following error message

``````
undefined local variable or method `forem_user' for #<Forem::ForumsController:0x5a28248> Extracted source (around line #7):

4: 
5:<br>
6:<footer id='admin_link'>
7:<% if forem_admin? %>
8:<%= link_to t("area", :scope => "forem.admin"), admin_root_path %>
9:<% end %>
10:</footer> ```
``````

**Comment by mickfeech** [comment]
Looking through some things, it appears the install generator isn't inserting anything into the application_controller

**Comment by radar** [comment]
Yes that's indeed the problem, but the code that is supposed to be doing this is just not. The output says "Defining forem_user method inside ApplicationController..." just like it's supposed to and the test passes, I just don't understand right now why this is failing.

#89 was opened describing this same problem and a way that we could fix it.

**Comment by radar** [comment]
I think I've fixed this issue now, was weird that `inject_into_class` wasn't doing what I wanted, but `insert_into_file` (which is what `inject_into_class` uses) works. Please try again!

Thanks!

**Comment by StephenZepp** [comment]
This still does not work properly. Failed today. Can you comment as to what we need to do to fix it?

**Comment by StephenZepp** [comment]
Answer my own question--if you get this error, manually put this in your application_controller:

  def forem_user
    current_user
  end
  helper_method :forem_user

**Comment by radar** [comment]
I thought this was automatically added by forem during the installation process?

**Comment by StephenZepp** [comment]
It didn't automatically inject for me (although it reported that it did).
Another small observation is that the documentation doesn't mention minimum rails version, but won't allow anything below rails 2.3.11 (from memory). I was hard coded to 3.2.3, but after upgrading rails I made it past that step.
Heroku still doesn't like the default installation either--it fails on asset precompilation, and even setting the flag mentioned in other issues does not resolve the issue for what is a relatively basic heroku app. Heroku does "recover" by enabling run-time asset compilation, but that's not particularly optimal.

All that being said, once I made it past those steps, it installed pretty seamlessly and I was able to start figuring out how to fit it in to my game, and now we're working pretty smoothly!

**Comment by radar** [comment]
@StephenZepp Having a way to reproduce this issue on my own machine would be a great step towards being able to solve this.

**Comment by StephenZepp** [comment]
Completely understood--there's nothing worse than a "CND" :(

Best I can do for now is to give you info on my dev environment at the time of my initial forem add:

Windows 7 64 bit
Welcome to Git (version 1.7.6-preview20110708) (gitBash)
Rails 3.2.3
ruby 1.9.3p392 (2013-02-22) [i386-mingw32]
User is model, but has no "name" field.
Gemfile:

``` ruby
source 'https://rubygems.org'

gem "rails", "3.2.3"


gem 'pg'
gem 'devise'
gem 'newrelic_rpm'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'bootstrap-sass', '~> 2.3.1.0'
gem "gmaps4rails", "~> 1.5.6"
gem 'annotate', ">=2.5.0"
gem 'ancestry'
gem 'geocoder'
#gem 'geokit-rails3', :path => 'vendor/plugins/geokit-rails3'
gem 'will_paginate'
```

Steps I followed:

1) Initial gemfile
gem 'forem', :git => "git://github.com/radar/forem.git" (from the readme)
bundle install
--got error about compatibility issues with my rails version, dug in to the Installation wiki page. Noted that the gem line was different, changed the following two lines:

``` ruby
gem "rails", "~> 3.2.3"
gem 'forem', :github => 'radar/forem'
```

bundle install, worked this time.

2) copy views
rails g forem:views (ran fine)

3) Forem Install
ran rails g forem:install
initial run failed on a migration --I just can't remember what it was, but it was relatively minor. Possibly not having a name field, although I'm pulling that out of my nether regions.

In any case, fixed the problem, re-ran install, reported that it worked this time.

4)  Navigated to the stock forem view. Tracked down the manual add to ApplicationController.rb (I actually saw it in the repository in the tests section), added it in to ApplicationController.rb, and it worked.
